apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: logging
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: kube-system
